version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://student_user:student_pass@db:5432/student_management
      - SESSION_SECRET=your-super-secure-session-secret-change-in-production
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=student_management
      - POSTGRES_USER=student_user
      - POSTGRES_PASSWORD=student_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: